// <auto-generated />
namespace coffeestore_online.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class coffee_store_db : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(coffee_store_db));
        
        string IMigrationMetadata.Id
        {
            get { return "202009131829054_coffee_store_db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
